// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2aPHsozcZ5pp4aNu6pa7SfJ75gA6zDAQ',
    appId: '1:801715214948:web:c6939c0c1516d490b51d71',
    messagingSenderId: '801715214948',
    projectId: 'assignment-13-b067b',
    authDomain: 'assignment-13-b067b.firebaseapp.com',
    storageBucket: 'assignment-13-b067b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFudjBtrJ2rtcgWs3uOoGihDeA6N3C2qE',
    appId: '1:801715214948:android:623e315546bb29bab51d71',
    messagingSenderId: '801715214948',
    projectId: 'assignment-13-b067b',
    storageBucket: 'assignment-13-b067b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCby0Q_WCKzRUmiALH2p8uEeOeNNDNmpb8',
    appId: '1:801715214948:ios:c98c88f7e92ee0f6b51d71',
    messagingSenderId: '801715214948',
    projectId: 'assignment-13-b067b',
    storageBucket: 'assignment-13-b067b.firebasestorage.app',
    iosBundleId: 'com.example.cyberlog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCby0Q_WCKzRUmiALH2p8uEeOeNNDNmpb8',
    appId: '1:801715214948:ios:c98c88f7e92ee0f6b51d71',
    messagingSenderId: '801715214948',
    projectId: 'assignment-13-b067b',
    storageBucket: 'assignment-13-b067b.firebasestorage.app',
    iosBundleId: 'com.example.cyberlog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2aPHsozcZ5pp4aNu6pa7SfJ75gA6zDAQ',
    appId: '1:801715214948:web:bea88f1853d8a6b6b51d71',
    messagingSenderId: '801715214948',
    projectId: 'assignment-13-b067b',
    authDomain: 'assignment-13-b067b.firebaseapp.com',
    storageBucket: 'assignment-13-b067b.firebasestorage.app',
  );
}
